### ISSUE TITLE
Add title tag to pages

### ISSUE THREAD

**Issue by ifarj** [alem-01/curriculum#12]
**Describe the bug**

**To Reproduce**
1. Go to 'https://lrn.dev/graph'
2. See the tab name(if you're using Chrome browser on any OS or mobile)

**Expected behavior**
Instead of url , use try to use title tag for naming a page

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version : latest

**Smartphone (please complete the following information):**
 - Device: Samsung A50
 - OS: Android
 - Browser Chrome
 - Version latest

**Comment by atlekbai** [comment]
Thank you, @ifarj !
We have fixed it!
